"""init

Revision ID: 001
Revises:
Create Date: 2024-06-27 19:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('hostname', sa.String(length=128), nullable=True),
        sa.Column('bmc_ip', sa.String(length=39), nullable=False),
        sa.Column('bmc_username', sa.String(length=64), nullable=False),
        sa.Column('bmc_password', sa.Text(), nullable=False),
        sa.Column('protocol', sa.Enum('REDFISH', 'IPMI', 'UNKNOWN', name='protocol'), nullable=True),
        sa.Column('vendor', sa.String(length=32), nullable=True),
        sa.Column('model', sa.String(length=64), nullable=True),
        sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'ERROR', name='serverstatus'), nullable=True),
        sa.Column('power_state', sa.Enum('ON', 'OFF', 'UNKNOWN', name='powerstate'), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bmc_ip')
    )
    op.create_index(op.f('ix_servers_bmc_ip'), 'servers', ['bmc_ip'], unique=False)

    op.create_table('sensor_readings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('server_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('sensor_name', sa.String(length=128), nullable=False),
        sa.Column('sensor_type', sa.Enum('TEMPERATURE', 'VOLTAGE', 'FAN', 'POWER', 'CURRENT', 'OTHER', name='sensortype'), nullable=True),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(length=16), nullable=False),
        sa.Column('status', sa.Enum('OK', 'WARNING', 'CRITICAL', name='sensorstatus'), nullable=True),
        sa.Column('lower_threshold_critical', sa.Float(), nullable=True),
        sa.Column('upper_threshold_critical', sa.Float(), nullable=True),
        sa.Column('lower_threshold_warning', sa.Float(), nullable=True),
        sa.Column('upper_threshold_warning', sa.Float(), nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_server_id'), 'sensor_readings', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_server_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_servers_bmc_ip'), table_name='servers')
    op.drop_table('servers')

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS protocol")
    op.execute("DROP TYPE IF EXISTS serverstatus")
    op.execute("DROP TYPE IF EXISTS powerstate")
    op.execute("DROP TYPE IF EXISTS sensortype")
    op.execute("DROP TYPE IF EXISTS sensorstatus")
    # ### end Alembic commands ###
