"""add alert sel event models

Revision ID: 002
Revises: 001
Create Date: 2024-06-27 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # AlertRule table
    op.create_table('alert_rules',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('rule_type', sa.Enum('THRESHOLD', 'TREND', 'PRESENCE', name='ruletype'), nullable=True),
        sa.Column('sensor_type', sa.String(length=32), nullable=True),
        sa.Column('operator', sa.String(length=8), nullable=True),
        sa.Column('threshold', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('severity', sa.Enum('WARNING', 'CRITICAL', name='alertseverity'), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.Column('notify_email', sa.Boolean(), nullable=True),
        sa.Column('notify_webhook', sa.Boolean(), nullable=True),
        sa.Column('webhook_url', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # AlertHistory table
    op.create_table('alert_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('rule_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('server_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('sensor_name', sa.String(length=128), nullable=False),
        sa.Column('triggered_value', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('severity', sa.Enum('WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id']),
        sa.ForeignKeyConstraint(['server_id'], ['servers.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_rule_id'), 'alert_history', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_history_server_id'), 'alert_history', ['server_id'], unique=False)

    # SEL logs table
    op.create_table('sel_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('server_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('record_id', sa.String(length=64), nullable=False),
        sa.Column('event_type', sa.String(length=32), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('sensor_name', sa.String(length=128), nullable=True),
        sa.Column('sensor_type', sa.String(length=32), nullable=True),
        sa.Column('event_direction', sa.String(length=32), nullable=True),
        sa.Column('event_data', sa.Text(), nullable=True),
        sa.Column('severity', sa.Enum('OK', 'WARNING', 'CRITICAL', name='selseverity'), nullable=True),
        sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('server_id', 'record_id', 'timestamp', name='uq_sel_record')
    )
    op.create_index(op.f('idx_sel_server_time'), 'sel_logs', ['server_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sel_logs_server_id'), 'sel_logs', ['server_id'], unique=False)

    # Events table
    op.create_table('events',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('server_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('event_type', sa.Enum('ALERT', 'SEL', 'SYSTEM', 'AUDIT', name='eventtype'), nullable=False),
        sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='eventseverity'), nullable=True),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'RESOLVED', 'IGNORED', name='eventstatus'), nullable=True),
        sa.Column('acknowledged_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_server_id'), 'events', ['server_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_server_id'), table_name='events')
    op.drop_table('events')

    op.drop_index(op.f('ix_sel_logs_server_id'), table_name='sel_logs')
    op.drop_index(op.f('idx_sel_server_time'), table_name='sel_logs')
    op.drop_table('sel_logs')

    op.drop_index(op.f('ix_alert_history_server_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_rule_id'), table_name='alert_history')
    op.drop_table('alert_history')

    op.drop_table('alert_rules')

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS ruletype")
    op.execute("DROP TYPE IF EXISTS alertseverity")
    op.execute("DROP TYPE IF EXISTS selseverity")
    op.execute("DROP TYPE IF EXISTS eventtype")
    op.execute("DROP TYPE IF EXISTS eventseverity")
    op.execute("DROP TYPE IF EXISTS eventstatus")
    # ### end Alembic commands ###
