"""add phase3 models

Revision ID: 003
Revises: 002
Create Date: 2024-06-27 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Report templates table
    op.create_table('report_templates',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('report_type', sa.Enum('sensor_trend', 'alert_statistics', 'server_uptime', 'energy_consumption', name='reporttype'), nullable=False),
        sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('schedule', sa.String(length=64), nullable=True),
        sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Bulk jobs table
    op.create_table('bulk_jobs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('job_type', sa.Enum('power', 'ipmi_command', name='bulkjobtype'), nullable=False),
        sa.Column('action', sa.String(length=32), nullable=True),
        sa.Column('command', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='bulkjobstatus'), nullable=False),
        sa.Column('target_servers', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=False),
        sa.Column('results', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('total_count', sa.Integer(), nullable=False),
        sa.Column('success_count', sa.Integer(), nullable=False),
        sa.Column('fail_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Discovery jobs table
    op.create_table('discovery_jobs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('network_range', sa.String(length=64), nullable=False),
        sa.Column('ports', postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='discoverystatus'), nullable=False),
        sa.Column('found_devices', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('device_count', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Scheduled tasks table
    op.create_table('scheduled_tasks',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('task_type', sa.Enum('power_control', 'sensor_collect', 'sel_collect', 'custom_command', name='tasktype'), nullable=False),
        sa.Column('schedule', sa.String(length=64), nullable=False),
        sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('target_servers', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('run_count', sa.Integer(), nullable=False),
        sa.Column('fail_count', sa.Integer(), nullable=False),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Task execution history table
    op.create_table('task_execution_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_execution_history_task_id'), 'task_execution_history', ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_execution_history_task_id'), table_name='task_execution_history')
    op.drop_table('task_execution_history')

    op.drop_table('scheduled_tasks')
    op.drop_table('discovery_jobs')
    op.drop_table('bulk_jobs')
    op.drop_table('report_templates')

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS reporttype")
    op.execute("DROP TYPE IF EXISTS bulkjobtype")
    op.execute("DROP TYPE IF EXISTS bulkjobstatus")
    op.execute("DROP TYPE IF EXISTS discoverystatus")
    op.execute("DROP TYPE IF EXISTS tasktype")
    # ### end Alembic commands ###
